# Generated by Django 6.0.3 on 2026-03-24 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_type', models.CharField(choices=[('APTITUDE', 'Aptitude Test'), ('ROADMAP', 'Roadmap Generation'), ('RESUME', 'Resume Review'), ('INTERVIEW', 'Mock Interview'), ('CHAT', 'AI Assistant Chat')], max_length=20)),
                ('input_data', models.JSONField(help_text='The parameters or input text sent by the user')),
                ('output_data', models.JSONField(help_text='The generated AI response or result')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_histories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
