# Generated by Django 6.0.3 on 2026-03-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cgpa',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='user',
            name='credits',
            field=models.IntegerField(default=0),
        ),
    ]
